travis:
  secure:
    BINSTAR_TOKEN: qEzK8YnF0vmAHBs71zfFAa2kzMye9f0CXCizg71+mBXYUFd0not2FAZaGmG856Yq/fz95TjfrybgUQHWQXaLJ8CQggDagIkO9JqSK+8Dbfwv0fbWHwHpuu5xwsEaq/9ghfXXYvaHKd74tGl3ZpuCpYolh7Ex7kiJn4arc+HcGMXElmwxraPueQViar9agNAD/oHcy/Nn3eu2NBSK2DXnBOLLUrbKAE4HFbuUPSwa/tTx/jDcI/57GoVFtSoXkFW/ROKHnmo+CIgN0+4QAL1NbMg/o57qXPzW3Efm5bMUx7SDQKJpaeoeE1cgawkLNkh22RIg5wKaySdOj634VSrF6mELdyBdoDXw/aZsGyh3jrn4e2ypladQP01b3gzYS7MkGzekcMgsD4rUusPSllUMPl+dD75LMXGwGBXjdWsfcinCN2TVDip2xKJSlDpyRc4TXvnfBSc3vr5kNHmYbTCnTEJxfMVp6uw8Gjuyqv3Wiw+WLHRV0vxz+inVU/u6DoIEUK2zHA6QkVpN+0wqeP0X1W0Ct/IPSs7VpeVv5gVI8KgiU5gHEdh8So8YGe/A4aNzcVopeUHWww8wg9jGGJapumqWC2t59gim4Q14zKTukETnWidWZEwGw5+785n/WXL0iOR3YpE8fJaXNJdzQLjlp84mm9v5ychERB/wqyc5O6I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
